name: C Lint Check

# Runs on pushes to pull request
on: pull_request

jobs:
  # Build job
  clang-tidy-lint-check:
    name: C Lint Check (clang-tidy check)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install clang-tidy 21
        id: llvm-install
        shell: bash
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt install clang-tidy-21
      - name: Run lint check
        id: run-lint
        shell: bash
        run: clang-tidy-21 include/*.h common/*.c --warnings-as-errors="*" --checks="clang-*,misc-*" --extra-arg-before="-std=c99" --extra-arg-before="-pedantic" --extra-arg-before="-Iinclude"
