name: XC8 Compile Check

# Runs on pushes to pull request
on: pull_request

jobs:
  xc8-compile-check:
    name: XC8 Compile Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install XC8
        run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/xc8-v3.10-full-install-linux-x64-installer.run
          chmod +x ./xc8-v3.10-full-install-linux-x64-installer.run
          sudo ./xc8-v3.10-full-install-linux-x64-installer.run --mode unattended --netservername localhost --debuglevel 4

      - name: Download DFP
        run: |
          wget https://packs.download.microchip.com/Microchip.PIC18F-K_DFP.1.15.303.atpack
          unzip Microchip.PIC18F-K_DFP.1.15.303.atpack

      - name: Run Compile
        run: |
          /opt/microchip/xc8/v3.10/bin/xc8-cc -mcpu=18F26K83 -mdfp=xc8 -Iinclude -c -mwarn=-9 -std=c99 -Wpedantic common/crc8.c common/low_pass_filter.c pic18f26k83/i2c.c pic18f26k83/pwm.c pic18f26k83/timer.c
